export const PROJECTIONS = {
  service_catalog: {
    name: "Каталог услуг",
    kind: "catalog",
    query: "все активные услуги с ценами и длительностью",
    entities: ["Service"],
    mainEntity: "Service",
    routeEntities: [],
    filter: "active !== false",
    sort: "name",
    witnesses: ["name", "price", "duration"],
    onItemClick: {
      action: "navigate",
      to: "service_detail",
      params: { serviceId: "item.id" },
    },
  },
  specialist_schedule: {
    name: "Расписание",
    kind: "catalog",
    query: "слоты специалиста на выбранную неделю со статусами",
    entities: ["TimeSlot", "Specialist"],
    mainEntity: "TimeSlot",
    routeEntities: ["Specialist"],
    filter: "status === 'free'",
    sort: "date",
    witnesses: ["date", "startTime", "endTime", "status"],
  },
  my_bookings: {
    name: "Мои записи",
    kind: "catalog",
    query: "все записи текущего клиента, будущие и прошлые",
    entities: ["Booking"],
    mainEntity: "Booking",
    routeEntities: [],
    filter: "clientId === (viewer && viewer.id)",
    sort: "-createdAt",
    witnesses: ["serviceName", "status", "price"],
    onItemClick: {
      action: "navigate",
      to: "booking_detail",
      params: { bookingId: "item.id" },
    },
  },
  booking_detail: {
    name: "Запись",
    kind: "detail",
    query: "одна запись со всеми деталями",
    entities: ["Booking"],
    mainEntity: "Booking",
    idParam: "bookingId",
    routeEntities: [],
    witnesses: ["serviceName", "price", "status", "date", "startTime"],
  },
  service_detail: {
    name: "Услуга",
    kind: "detail",
    query: "детали одной услуги",
    entities: ["Service"],
    mainEntity: "Service",
    idParam: "serviceId",
    routeEntities: [],
    witnesses: ["name", "price", "duration"],
  },
  booking_wizard: {
    name: "Записаться",
    kind: "wizard",
    entities: ["Service", "Specialist", "TimeSlot", "Booking"],
    mainEntity: "Booking",
    steps: [
      {
        id: "service",
        label: "Услуга",
        intent: "select_service",
        pick: ["serviceId"],
        source: { collection: "services", filter: "active !== false" },
        display: ["name", "duration", "price"],
        groupBy: { field: "categoryId", collection: "servicecategorys", labelField: "name", iconField: "icon" },
      },
      {
        id: "slot",
        label: "Время",
        pick: ["slotId"],
        source: {
          collection: "slots",
          filter: "status === 'free'",
          filterBy: { specialistId: "step.service.specialistId" },
        },
        display: ["startTime", "endTime"],
        displayAs: "calendar",
      },
      {
        id: "confirm",
        label: "Подтверждение",
        intent: "create_booking",
        summary: true,
      },
    ],
  },
};

// Корневые проекции V2-шелла — верхние табы, между которыми переключается
// навигация. Порядок определяет отображение слева направо.
export const ROOT_PROJECTIONS = ["service_catalog", "booking_wizard", "my_bookings"];
